language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy-snapshot.sh
    on:
      branch: development

env:
  global:
    - "DhlLatEVm+lx4N3+OnuRuZVufVmok1ByJOnANA5Q7kbh/tRWGBcUCQGp5jSFLAsHhO6Kxgun1G6TWWDcqbjbkCJ2U9AjoS7oUUQ94BzSI0yrYWsdTaKLuFwGNrU1aM3Q936Y2JSk3v6Tkkpjm2k2kInsZBGjgvPCLe5Sn6Lag6SitVhsMTUqB3nW+sIbIuaJWnM1W30adyHIWn9k3zWeEcIM6faNjyqe4bAOaH+6HqbDKMlnepPIfMRSiI9ACaOp21YLN9eQXZovG1h0lZhEYu73VMQmgPjiSk8X7FgC+eyQciHdU28E16JI0Ejwkuc9S6XF9NDFigfj9MPLYtqbrhKNWX7L5kMxqhWBhjyg0xKMA/zcLz8AZovmwiDI1iErJZQCw5le0p/HFmTs5o67oNAF077dkMbHJvbdogjLVnJA5NqTOMZYvJ3u1BPHwQUASFY9JYlmpXdLYbfGxp++Lrl44MmidxOaUKnbMN1EXLKzqWeI37MAokJZ862NY1FHEXcEJgQsnzapd9zgdq7zoP7MXDBZY4b/g/1O79g1/wLF2SsMH8A9W89uq1J532CIYR4EFjLpR33iwRWnSbwxRGW0N9NwBB+aG0qtPIaEI71lw4eqwWxFkbMe5Jf6d6+h3el3VS18NAXyNIJJ59Dhmrs7tbrrKJUh4eZu/aTZpIs="
    # ^^ SONAR_TOKEN
    - secure: "b1lrwVLh+CJUzblf28WWDACv/GsQvjjfyu+nHyU37cpoZhMLrixh+q9uzE1uAK8Zh2SlWPAH1DKNccFSC9lf7gINcLebqDs442Rwi/o6N16LA8wvto0WGV/Ye+i+NiJfBYztOUMr4FA22BAfNxkAXjc3Hppp8oA8F90MwC+TeQHP9/vNPUbRCT6rOKKM+0oAIMqzQ65voRcTxx0rDEtig8YwFj7oN5U/SbfMi1GYWUb1MNG8RRg6qVahI0PFl7LmeJoTPdmoFv/8Lyqq2m7xcM6AQnVcY4U66331hlmHQfbRrh2ILuFpqp6rI9SuytD6U4X0/WuNa+k4/NhjdqpboX1ycNblJGOaG/PmTP7eGUDRcBO6xvhKprO+4o2ONHh1aVO/FUTDclEe6wtrwBiK7PyuIu0m1CZ3KfzQd5egEobwWUztEc4uhzy82YHABCKpcL9IVDD0l7BOAVoX+owUDfBmi+16lfAsmBLqBzUcRuS9MNLCHhoubh6l6SNB4eNa62PRIpo1m6HG1Mc43EL8nhRNSdgaZgsIQAaWXAMRO1qcsCIRqsXHeTIb77TStcOW8TUeLzWPDlaWtg/fSQB4lvZ3+XJY/VagWVAbNm3lscUwUMQaClfnRntiJEaQ5i0XT2HeZQs4Joaal8/nms8dPlDqFFwSbogxBpj6861Y/uM="
    # ^^ GITHUB_USERNAME
    - "mKNIyAiyO0Ypf4ItRRgkRDgPPpjR/lHDDrpSuGXBEOScA3Bt4oxyOdkllMFT0760odv9AUkRYbzC1eXNCC/7x0fhTYe4NTbt5GyiZtPhmfwPaohwPNAKUla0VK6oXrzbbsnYsIuadMSRQCktvxpGuf17sS+7FndssEvaeEwcz3fQVooLJiFjpe/aorgvZGecVhuRPYvNEcO8uAb0En0y+7HD2pfdxCnrOQxjYhufVfLVl1pTuWLU1EBsgOIY+m0RQp+BBzWw+A3E3rrcfa/0ia+otp68OKI5il6BDp+6zONrUv/EmIOKp/zE8+JQX8cVHrkVNtuyxChv70MVyklwQ094jNlVjAkyvIRMjWsuT7Wyo882KcTbp+cNxzop7pSKzi2ijw16QKU2kIMBFc2ZlTesTQ9tlhkB75iD0stLFz082CA36Zc0mOhrdp4dD6+sQKURBdcY+F3wNdfAJZjVyH4HzxgCIhdgWLAk/6wT0NSZkrtKFe/ByeYK1EzljRV9AAoTHsmG3cR4OFbOpN/Ig4w8EAaiOi3jTQPNzh0KdzTqJR9eQdgdGLRKBoWQEs1zhEjMfW+cn7Sb+ZDFHKQ7/AFoG2qFJsum6HgCTaADDtnqc7ilmB/eLAcwnlosXzFbwOHtohj7Jaq+rLk6k3WPsMX3g47OUik0W5Koupahocs="
    # ^^ GITHUB_ACCESS_TOKEN
    - secure: "ewGW9/mxapmGKCgEeDqFdsMtbYgvf2/LxOS2GTzhFOsMLgvRkE6XE/cthjWeZGK6j8lcf1hWw5IWL7vkrzO2Yoi9RionLKJs7RWSCxlPLv+LHS1v6Eh+7raCD0ZWtj7WQDKACqOD3QZxCrKG4DTTHZrAKMrZZ8tmy8b16lx6sAIkDV7q0D2FHlM4uh5jpA+ntBQDAAtrka401sav4ruZmEHh4RBlrMCTfAFPedKLMR/AjLGWHg8kRkQ/Gy5jnztW4vukpPTvE7XXdlSYxmZ93vIMxF3tdDIta6xx+b9RaKeuzxea/J7ayRqCm5T7A3GdVu7tf9K2wOtBo1pmaUfPvbyr4Zj8S7H+Ntw61NJlvoy0C96fZA12LCjc+c1ey758BzYCuNI8izN9TQ96cd8MrwSw5wdgKG0Lfizt3UF0O4v7VpSQ6HAWPvJbYnSUtwWmVGgmDBNrqSaZDyQi989ulugoOb2P3W525ny/ks4UDx2+v1M4VrS7FXM6ho4QzOKNCcd9qWrY4RrTyG1OZjhKhVieI1hItQKA0bHqCofaSD/y7CDFWNoO+cNNqoGgdSMLFBGstEV6UgItn6uBYjlfV19CoLYfRAEXBsQvbJgtoOd3JaPBZMeB1kBxCfHia1NQpke3csFobzrUiE8ekk4bk74AQ+MlcyLYCWlaSS5KNcU="
    # ^^ OSSRH_JIRA_USERNAME
    - secure: "tC1DiWAcIpiuedA6rLnnqw9iSV4HGRjTc62ZCJLF4VUknffbx62nwHBmsF5bpF3UIjWFEbfjrR1sEBikcohPX5Broqbsvg+v5Luir5geg5UesayFRLerroGECvVxZYFODKNWTL/It72k5pr3uPG5vVct5ziOhgT8D+LROJBf30mRMSevXxDexA8GKYFKlxH7L75k0pnXI+0rhAKqhFXmHQYzngqMKJSab8YHELUbFXJSmfT7otAanZ+BRvmi4Dv+r45a9Y+iRuL+Y6SadFxnSNPAtDjFV2uhOw/0uMhaHuKJqYE5fwLkHb0ChPHHWE/HiERRnENrQih+rZB5L0YKQ7QWeCP8DBxOWd3hfctcckEi+5ZPUNh9uIy9+pEJoY+TlIFuxe6xvj+b7ftWXuxhE/pVmJxx6Fa6z+dDv0a0PBY0jn6Tom5sRMK0FdJ0OIHanp28dvnwqbYGMgfeUZC4sqbss2iYQEYcJNU8/5fD5LvEEKASkb02aMB6pJ9HzVO05oa4yKMIohfPQGFBtJPpxbkD4FmfGXU4sJHnhUKGc0iycN4IYJdXmAXrG5k8GDpWm4Ts4PY0BACqmUyDHu8WiS3CFM+ujrrHvp2nsqghuRwIje/kR30Q2HHR5XxeJ+DzQJX2C4yTj8kPSl4OBfvZ2XIoCM6AE+BfK9JOxpmV8BM="
    # ^^ OSSRH_JIRA_PASSWORD
    - secure: "GjfWbvn0zrnSbFdP175pP7vz2FiYS0Kq0yXmo54oUAf2VDBCIRWxC6AmFRWOmH/IpPEIJIrJvGokSk+C2FxEXAoi+i3DRovSjQSReF2GQBh591JdJTKqHEIbJiAxgm6rj/5mVwuSdqlaRIK8MFD50cKS7c5k0sHvQ13qASUgVEcF2JIb9+S7g4Gr6GxllPRiuek4aDTtYyjcMLjrpMDhiy/3b9JJ55hSnJrLskNrt2DmQ0MZ/ganwmZzVeSup97LoUVwofwfCj4+HTUT5QuD4oXAkTOJMrrnJeqXYysV7JaTglUCayPhsaU7w7xPqWzgPaXVS6pTbUugWG5/XGI1azbz4OzwRzI3OcPsWLq1mdF1Vf0lvXNSoeGt+trLdIeZavrt2u1a1lxyY3xicEl1VdzZO5wPTbVuEuiHPQfMOgREavpdRBS6nYGxWrBr+dHZyd5R8Q/7RmiALHZhHHRR+AMuTSoq55xhXKjBamPDBTzdzjQSJH0deY7WGkQHQosiqcs1vWpfH6TkkxXwQfPCx5y1XvppBKV0+W60Ker2Ye7L2IL4Zg1hTG75fnjk/pDWKHlZaVpQx1WVOdaUf9vvfPHy/aHCm5iCZelGIkdyw5CFVRqUzl29Sf2f332V/WwXnaczYv5s41J6Lx2TALBH5qzSm9sDPrDP+jHbgNZ8GuE="
    # ^^ GPG_KEY_NAME
    - secure: "o8AoDyKp5omsv+VtRDU3Upcs35Fhf0D6dJ7JNiyrwnQqBddYUdDUNWeb/RhhXUBBTDhNHa9RphxjBAsDtr5TGPQ69e49I4j9jV/rI2y1WRLbVO6LADzZAbO2nqs4VlXSedLOFv74ohkI7lHdsm/jJMPv8Lle2IaAUZNaX8HyrgkxLfkkvzKfwjEF1TUtIUCYMPabLD2s7OyFkoNsqJ2UxA/0ewdCzNd3qjNijjqaX0O1QmfeMeG5JC5Ir8npGqe5a4pVlEj56Z0ebGTsxJfMcMewZRS5ywIM9RY0cg8It87UVaWbnfmLCPKNQgl2MwsJoNeRPGxDCo8qYa4sDJj7Ibd+H/0Y8SVaNTeh9HjQDbZX092R9kFL9w+mFgIgJxHjznbfxKzSdM3R+ZrTDj8aIRqeVXTNGpsuHiXIrWmEuQWmrQvIek2dTtZNNrN5WcdtibJMoRdXv6l4twMfEWiz8BAu4TSULEar6FjJt1ScCh+FaftYXN1MexZwbgq2bsCLH71MIG1ePZm270rAbvZCD10DAwvsRO/RcOOZui6i3Fe263F4IgOViOwLblRnWwSBAW1gAF6WerDDWU9fQMKaFEqSFq95v6LiJKlZSe2IbBZNK17G6Odo9HqOFFP/fqk2nq2bkQUP58Ank2tzsIhSjMW7oyiOn9V7EaTh8FBAXEU="
    # ^^ GPG_PASSPHRASE

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: ${SONAR_TOKEN}

before_script:
  - git clone https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/mirioeggmann/tbmelabs-deploy-certificates.git
  - gpg --fast-import tbmelabs-deploy-certificates/tbmelabs-deploy-key.asc
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean verify

after_script:
  - rm -rf tbmelabs-deploy-certificates

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
