language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

env:
  global:
    - secure: "mRTPwCaebEbKQEr5vyvvO4UtwwKuBFRlu+vKYUEeBEWygc4UOLgL3qjg+5Qtj2v44zq25+xvn2FH+MqBtN7PUr4TGQRlzaPLDhRPUipHqytT20P72YOHj1D9S86n3yEPXz7F4NKYY/wd2cJAPRU3TovMjA6TZ39KeGOvst5eHBbZAA7kz/RswpdpTqsWLdt2mkWMymsfReDBmn21eUpVYtGTeI6+h/y8U25LBHxF16tFWNBWMQn5d6DVPlqi6u0VhWjlSPAjA6VDjIK99w0YYActQ4mLXGiOq3YOG+DcT+zozARtLuRqE4hbhTKjMRnPadH1O+XAl4H5lrMGH5R05FMca83XMPRP11LgR6G/v5qfW8n7wwJGQpOsjaTFh0uQdbyr3QFbfqL+yhDTFFjW7qo2zvGtNjgduTo7/La1HTyFGwrHqgMMGzm9oOWEf2btGKG7ZEUsRDDmOxH85pWBxlRGPxf/uImVwWJUpJdnnSUlBGbsHGDU03PS37FY7zAOmM3A5ks7ye+zg7JWnqrZfkTOGcO3Gze9PTrqIMB0PXfzHFyXMsVKErX1EnGGAKqpAdsA2UbjGZaaAQMdtFQO8SSD0jl68Iqw/70Q8j8PaIhjcikqprIsNxSBZ+E71pcO9XvyGw2HnNFDFfyL4sml3jWy75TkwODY2vI8e3nivoE="
    # ^^ SONAR_TOKEN
    - secure: "CfagANdcjT/MSPDigBvlg1Milh2dymFFwZpfZStiQMVoI21y9ykj6WK8zCY2qaO7fve8gTgqFruEQ6ua6TQA12vGTnX/FZiw7NXIr4hrM8nMR5awf9kWDtbDlZaYFko9hMD4QxAuwn8+Gi48aKpGeP2nxgwCMHh1JW0JXquBbt3n3exQTbVTeY4s3sz3U486sqAgv8JBLKJ7WHvH0z48Jn/Wp+OP0vaGO0J/feoPxtkuG6TmXh0nhpiXhatWQVwIX2Ju1bFZ8ccn7zrMcLoPnBVkofVGReI7jb4lwn/E84uVucgYGmA3++EYtP+1Z72kFb3dRRePIAjUlNPZYMNfGkd22BqepcqE7NXFrTSJMa8mwzFmfpcYTxx1gJBjPod2EOISCMx0+nxNfYlQPLw4Ehn1wdGlhVQi4rGjcHt1RhnMgR94qgI/g+i/Z3C5sv+q9d6KLX5ac3H4nfLyfa9pTEOzKrtVJHQAH3QKcEXeMX6kbhafNe++BEcxXzlsCnrJQ7UDswxvobpGT3fOs4YLg4GTep5ZXGb4tUeO5RroDfssTwrRyBRLmZkS+EK37qBSKeQageX2GsthkUwkskwK3jCCGmJoPFrU8dmJ4vRbVL19JYIjSuoK2UHOSKg1SgUFUEgNDsnNaLdZcsRgJjwoYC0fHno2VHUPBsSvkQyaGRM="
    # ^^ GITHUB_ACCESS_TOKEN
    - secure: "VoE6pZohle083FEva+XA3d7od37X6d0J6Q3olh9WrA3lgBKH5cbKhApaqs3j9sWFijYm6Jt/PqA/K0UBS2LBoSveGY2dM8tHqJZKqbalt3HAcmlRlqmmH4mTuz3qTrQZvsBhidQpMkQs33m9texySziEYz9UFbqGNAEToKibj5u4WObmn3wJAzzxrE0H4NcORpEvG2aKI0arjQ93VSjuOAgv9TYF58DRRr1oyaAk2jxWpQ/P3qZoECa475lVwl22EMHnCafbvkrwCNCLNJT+s/z59pZruQEMicxISkXekNyH6ZURHJtdCcCLxI4/ni6vwiiWMX+8dI36PqD2XeXJJFfAXmjw1DuwooXsV0pWYBHgxvzPn/OPzr783+mrs2KpW8HT2nG+dNIjL8qZAbA9d5Yskfg86tlEn69B2Ban+PjSUNv+3OP6lNXJl+rKGFHr8UmTGDJOkQdSX5bP5eZrqfCNhWj72fJdPfop7ESPWH1JOv9aSUnLZcg4z4QnJaMrgUBEXetLhpcL0W/DpxasFM6VGr9+5rbWR71BXtmOZY/n5zkxhz7T7t25kY/V8RtKxxAyfVjzGgkeNVxH3RUP68bb5rL826U8a29I4rAebeq7HemUWHvnwd+TG6Imz5xum2400DVWwJiuEnULSNJbpyqhVmPK/Spd/CYkK977W2g="
    # ^^ OSSRH_JIRA_USERNAME
    - secure: "thVtP6RD9oLKOUN7da9HvnEtzyFPoasE4BuKpsIEm7L5ArhoTVF4eIgBBsoo2wlvn5oFgSn0PZD576qnNrJGIlLGLSyt5Z4GyWaYLCLZfRvGX1sfKQJ1jo2mFN6OFGTBJLY3tq401xd32B8IsTOrkR1JDRvzrtSQh7C+/yaHznvMF5f0drU4ob1ZnYIxoDN/yqRS2hoGkZx47bj9cdyylcrwWUny5ypJ3u4GO4+vYfmEKO4Ubjn13F8r/ntMq25rPdXvjdEJlkCQ+yuigpJ+33Osml471W8VcjnyfAuwMP/6XPUNpdiL303P08rAo+ohjMLgFWKsKsHT/ybxRWvranSfAvlgUtrdpcfZso7V+vR9h8ii+B8vKOcysyzUfoIPQ5gmDq+MBDwcVo3r56l9haKUS9gu97LfArVIhSG5PhqcytUKxnQAIDHxl+bhpgcCMoxqeMcq7gfb2Lao1kLczV0J/ZHdIiiI3jInKLmEb+koQkuViiK033W9OTtAtu5acPqhmGdEa1s5kMFNUROBFEtS9VUkmi2MsTbZNke6B5VAdN8I6bS29fOkc4Zzn7rUFhGBWLihm2aWMJeFVKImaN67+noKg3Chs/BpX73Wg7frzJVLQ+3HikktOiiejGcwPUSpeVl8+tBJWRaHJHFS/3sLu7sIxW5tdQc95McFcc4="
    # ^^ OSSRH_JIRA_PASSWORD
    - secure: "Cbek3S9RCs9TIuUN8deQ0ZXU5PvANzA0hNhq54Y0e3/1Dn4QA7rIPeDnEnSBKWQwD/TPjSBPLjWID0AC+Xt97TK4qfd4T8h6NNP8k0FKN6jqDuHYTWKaj6odgqL0G10EDCe+1pxhXphesvIjBrZ+wVTqa/IMv7lNpI6SAWN7HIsU3HWI/Jlk0RqPKyuG3EYdwKsX7ZNECh5cwVOru77U+EFiPs/o25NhTh5pTPg29lxEihwqaRooWsyHiqG9ZP8o7+KTO2nAUJ3HOtODNy3+giTZkVk104JOqJ/UBCMvpYXvoMwfFK/geBIBdMfaRN85NYC2IMDOhvzVB0pJL6hl3UaTNqXoN+RLr6gMLdu0Xniop/DaA3GP1MOCJ7A1g4/g1htwLDqOYAzzhfzWbtySFpvVM1fWHw6+zU+fxn2Wrl2mWvsZvqWX4WslHtzXP7lAjGPJRK+Z8xel+KjkKxdv3l2XQtPDa5/95WL6aiwcxB09IMWxIFE8GnAcqjaLkFODvm1B6siKnMhC5oxIQFYYORukvIn2CLfk8GEHRuaMFaut65dbKrceUgGGYfk9FZ6fR2RC+r0PA8iWSnDOQwTTtbRcrBa2ihXgm/uetyuYdrBItohYSmXAvgOtuzVvgmxKcw43Iwg3/inzhD6f/RNr65Q2HfcAaBAyPvViJCfxiEg="
    # ^^ GPG_KEY_NAME
    - secure: "O/EC4BkyhZz6KBH+qiemLgaj96OaCAgTzwv69Df4OfqTDuTiTqfi5gIewbxkBR818dxtrppiCPD3TZ5JfGZ7+YYvTNC23OK30D06pl2ssI9IHwUNWR8UrYq+o4uKUj3DErsKtNwLctn5t42vsq8Xkd06l+JDmzRWIQXMUuoHGRgUnTOHsAoqePqkMUyEQZATuitGwaiqGDlNDyM+NkCS7dry85ySSMwMb3PpmGJYbX6CDUbwkh1kXF7w90X/4ExXC1ogPFllsm1a34IdmjEx2pOfjcDTYWifPmbJ/QvfCMo1FOjHrrZkxrOimlUKTYWklARS2X2iSmaCUzZFvgxOPHsHmC/oz8+XS8WvsMep/q3QAsPcaiMjFW40/QWS7PVm0KxXCV9ggyiuVrXauGZ9cfd8Fzd6HRRIyvmTXrQI5hrRUYEn/I3F5U7Q5m4JbWW2Du3iOM1AAbvXSch8NAv1di96EQF3Pd/7D6/I02kgLAnCLSSWgl6ihZB+2JISraJxi6E8FYmzC4BC8lew3C2iuczyz42k4MSv5I5jCqT9MPm4XS/xlaUddDPWzWM7yturcJgNRsu1cdenf95Tml02hn1TZDkQrMG8NmNiEmLA6kMAWkYQNhRAM/NSfpmzQJFclBUvjNrZaky3m+nV3J3IbRhAjwUF91ROm7xPYELURk8="
    # ^^ GPG_PASSPHRASE

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: ${SONAR_TOKEN}

before_script:
  - git clone https://bbortt:${GITHUB_ACCESS_TOKEN}@github.com/mirioeggmann/tbmelabs-deploy-keys.git
  - gpg --fast-import tbmelabs-deploy-keys/codesigning.asc
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - scripts/deploy.sh

after_script:
  - rm -rf tbmelabs-deploy-keys

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
