language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy-snapshot.sh
    on:
      branch: development

env:
  global:
    - secure: "mRTPwCaebEbKQEr5vyvvO4UtwwKuBFRlu+vKYUEeBEWygc4UOLgL3qjg+5Qtj2v44zq25+xvn2FH+MqBtN7PUr4TGQRlzaPLDhRPUipHqytT20P72YOHj1D9S86n3yEPXz7F4NKYY/wd2cJAPRU3TovMjA6TZ39KeGOvst5eHBbZAA7kz/RswpdpTqsWLdt2mkWMymsfReDBmn21eUpVYtGTeI6+h/y8U25LBHxF16tFWNBWMQn5d6DVPlqi6u0VhWjlSPAjA6VDjIK99w0YYActQ4mLXGiOq3YOG+DcT+zozARtLuRqE4hbhTKjMRnPadH1O+XAl4H5lrMGH5R05FMca83XMPRP11LgR6G/v5qfW8n7wwJGQpOsjaTFh0uQdbyr3QFbfqL+yhDTFFjW7qo2zvGtNjgduTo7/La1HTyFGwrHqgMMGzm9oOWEf2btGKG7ZEUsRDDmOxH85pWBxlRGPxf/uImVwWJUpJdnnSUlBGbsHGDU03PS37FY7zAOmM3A5ks7ye+zg7JWnqrZfkTOGcO3Gze9PTrqIMB0PXfzHFyXMsVKErX1EnGGAKqpAdsA2UbjGZaaAQMdtFQO8SSD0jl68Iqw/70Q8j8PaIhjcikqprIsNxSBZ+E71pcO9XvyGw2HnNFDFfyL4sml3jWy75TkwODY2vI8e3nivoE="
    # ^^ SONAR_TOKEN
    - secure: "b1lrwVLh+CJUzblf28WWDACv/GsQvjjfyu+nHyU37cpoZhMLrixh+q9uzE1uAK8Zh2SlWPAH1DKNccFSC9lf7gINcLebqDs442Rwi/o6N16LA8wvto0WGV/Ye+i+NiJfBYztOUMr4FA22BAfNxkAXjc3Hppp8oA8F90MwC+TeQHP9/vNPUbRCT6rOKKM+0oAIMqzQ65voRcTxx0rDEtig8YwFj7oN5U/SbfMi1GYWUb1MNG8RRg6qVahI0PFl7LmeJoTPdmoFv/8Lyqq2m7xcM6AQnVcY4U66331hlmHQfbRrh2ILuFpqp6rI9SuytD6U4X0/WuNa+k4/NhjdqpboX1ycNblJGOaG/PmTP7eGUDRcBO6xvhKprO+4o2ONHh1aVO/FUTDclEe6wtrwBiK7PyuIu0m1CZ3KfzQd5egEobwWUztEc4uhzy82YHABCKpcL9IVDD0l7BOAVoX+owUDfBmi+16lfAsmBLqBzUcRuS9MNLCHhoubh6l6SNB4eNa62PRIpo1m6HG1Mc43EL8nhRNSdgaZgsIQAaWXAMRO1qcsCIRqsXHeTIb77TStcOW8TUeLzWPDlaWtg/fSQB4lvZ3+XJY/VagWVAbNm3lscUwUMQaClfnRntiJEaQ5i0XT2HeZQs4Joaal8/nms8dPlDqFFwSbogxBpj6861Y/uM="
    # ^^ GITHUB_USERNAME
    - secure: "CfagANdcjT/MSPDigBvlg1Milh2dymFFwZpfZStiQMVoI21y9ykj6WK8zCY2qaO7fve8gTgqFruEQ6ua6TQA12vGTnX/FZiw7NXIr4hrM8nMR5awf9kWDtbDlZaYFko9hMD4QxAuwn8+Gi48aKpGeP2nxgwCMHh1JW0JXquBbt3n3exQTbVTeY4s3sz3U486sqAgv8JBLKJ7WHvH0z48Jn/Wp+OP0vaGO0J/feoPxtkuG6TmXh0nhpiXhatWQVwIX2Ju1bFZ8ccn7zrMcLoPnBVkofVGReI7jb4lwn/E84uVucgYGmA3++EYtP+1Z72kFb3dRRePIAjUlNPZYMNfGkd22BqepcqE7NXFrTSJMa8mwzFmfpcYTxx1gJBjPod2EOISCMx0+nxNfYlQPLw4Ehn1wdGlhVQi4rGjcHt1RhnMgR94qgI/g+i/Z3C5sv+q9d6KLX5ac3H4nfLyfa9pTEOzKrtVJHQAH3QKcEXeMX6kbhafNe++BEcxXzlsCnrJQ7UDswxvobpGT3fOs4YLg4GTep5ZXGb4tUeO5RroDfssTwrRyBRLmZkS+EK37qBSKeQageX2GsthkUwkskwK3jCCGmJoPFrU8dmJ4vRbVL19JYIjSuoK2UHOSKg1SgUFUEgNDsnNaLdZcsRgJjwoYC0fHno2VHUPBsSvkQyaGRM="
    # ^^ GITHUB_ACCESS_TOKEN
    - secure: "mpyp6J3qbMicEud98mPpDSTI1aRXMxVDNv9ywd1Mi5Y1Hj1NpOr9bisUgQ3MekFYrRm0YxbmYQ6NvUg9ZpXZkvaoaAScfgOqHKM5DSERT1D6okj7/5htYCG9RfsMkZLvbl0nz/zjlNttxJpO15KQ0POvVMLqAxkK4tO8oxhfnT5jzVfdST1hxkDb5I71/nugtvhqc7PgQt9aRtBslYl6QFf6ZitFFUeT8jziU80kyQu3kgoNfWYeQaxFE3bug6bn+mEAkMSvBc7VnWmDDL3BQrARW93x5+fOKrlis++PNz0BXTNWGIJXHS5XE5BfKNSWuX5bS4PzLP1ktJWR9M9PsVrEbboSrOZwWo31VrBkOCGJaqhdLqQQ48ZbB21zGZ/zaP7VJUSpxaoxuwn7ofg75LtV6g9N6D82122whcAe3Uq/E1qM8TONhhsLZZ6IA6KqbqRAJwMkqCp+eoWJevyidXU4k8k640hXVkiNXsz/1CgRcoP9vo0zVxCofAs8cJjMbOMAZR3Ej2s+mXs5ww0MHCPtRQ/cTOrCzhcScCFqJjm2K9tR7ZvW03mZv1rI8iaQ1csmXrOBvm8NnE5/rU373DaIzqF+qGKj8Yg3wqD5lGvC86Tu+BlSvwfLXiGZUZQUlvit8oqm8o+6gIjU1ybyVGrtmo8xDtTOLDX99tN3mUU="
    # ^^ OSSRH_JIRA_USERNAME
    - secure: "D72px4s8pHMmwCSh36Hh0AeQ4vLubNfRa4z5QkgAOWP3AKrgAUfU+5ZI6Vf2dLvo4gVOYdYDCpd1WGpXUtTg/LuqmmkdYVsu5w2riG3pmNkZTOcNtI3iguBKAMtnf+ElwESIvF9aSSzIxs9ilhH8nPRIYZ8G09c+1SfhQ6VOC7ClR3RCC9YlptefP1j5YkjdAtdbbnWstxMhf2xAStCUQPU4mLof/q/ac1iazo4PdzCT/kJxCe2GehlxUeuXQfRfI8LIS3Y42Cep8cYCd95vkwSN8eliwmI63S7hzyDvkBBqYEuqUWgqGt+prCjOPb8lkWyVPjd74nbA8ZaK0IZBjKbDE0zES229JjXVW5TXHECGQWZeBcnI7CNK1l4mGeAVOep6aQcj6YmsJA0K5OpyLKpUzkhQn/m/MSTcvhraz7EOKrDjh5qgHSIwEG5heHcvLbYW7eeCNCIqf2IKOGn4pIopolzWdxdBozk89xQY+2QnRAtCpmocexRQWI6pJhbtcieKMd34GjFInLhZ312wxqdfVRxWLU34cAEkYYSxrHy45YIIjNv4UYLftg9af1JowaoaJTnHNJKz18cjykNo1n0NqIt9GAXPfBH+VtiOol6kvHcXtlQx5Kvxv7kBmZqpoS1LipozKsEhawiIl5xyiVKP/cTFvj5GA4Xjxr3fdSQ="
    # ^^ OSSRH_JIRA_PASSWORD
    - secure: "GjfWbvn0zrnSbFdP175pP7vz2FiYS0Kq0yXmo54oUAf2VDBCIRWxC6AmFRWOmH/IpPEIJIrJvGokSk+C2FxEXAoi+i3DRovSjQSReF2GQBh591JdJTKqHEIbJiAxgm6rj/5mVwuSdqlaRIK8MFD50cKS7c5k0sHvQ13qASUgVEcF2JIb9+S7g4Gr6GxllPRiuek4aDTtYyjcMLjrpMDhiy/3b9JJ55hSnJrLskNrt2DmQ0MZ/ganwmZzVeSup97LoUVwofwfCj4+HTUT5QuD4oXAkTOJMrrnJeqXYysV7JaTglUCayPhsaU7w7xPqWzgPaXVS6pTbUugWG5/XGI1azbz4OzwRzI3OcPsWLq1mdF1Vf0lvXNSoeGt+trLdIeZavrt2u1a1lxyY3xicEl1VdzZO5wPTbVuEuiHPQfMOgREavpdRBS6nYGxWrBr+dHZyd5R8Q/7RmiALHZhHHRR+AMuTSoq55xhXKjBamPDBTzdzjQSJH0deY7WGkQHQosiqcs1vWpfH6TkkxXwQfPCx5y1XvppBKV0+W60Ker2Ye7L2IL4Zg1hTG75fnjk/pDWKHlZaVpQx1WVOdaUf9vvfPHy/aHCm5iCZelGIkdyw5CFVRqUzl29Sf2f332V/WwXnaczYv5s41J6Lx2TALBH5qzSm9sDPrDP+jHbgNZ8GuE="
    # ^^ GPG_KEY_NAME
    - secure: "DdGxwBytLhGXlGXiY5Gny9tUBuhIN9i5H5bz1CS5pXSbvCgVk6LH+QboW8pPoMR0hPbK46pslJ6HyjtkceznrY1AmDr/q+hzUkolpYBjvbu8VLDRGBsn9tkxsOKzcr84Qaf9mokZxxVw6dNKLbbLLXScaEQVrnIkRtTK1G4ayubWVzWsXAk2hq+WO2jZPFTEGA5OSbuI5YsyKajqSCCpnOUgo6Ec4H3nJb8/3w+i6UMYCrDgf2XV1WcbyokV2utUNnd3z9qXnvAw8I+MppCW0NfWuLvEVGTBRIcBPODVhJCsbvQ0nntw952UqENQ6mHu3n2KKO9XwDtvb8sLwtw9MxrIP9vD1JxBrjks+Epu6e4HZTyd4tzWYZqsrPupyTtRy7M8ALfBfb1P9J3XU+84C50ZwJhaPesnexBPwsRgUeP/jBz6Zx39DpFqSVmviKnCF2jIrbK49Y8ZM8vNUR2uaYp8dqwpe8XnX6nX1BadpMNAKAGACoOZbevjFPAeemjlO7WoSrQd8GNEX2A7niKDfvCJFB6eqyBiLYczi1zSMQO79lW4HiU0jZ20Oh9m9WLV/yAu8yhyH/zLJKc6MvA5UeJ3ukJjCDYrrHDW1m4n0rtir1PejhU0mMw61NhxZ3s0GKOmYOtH0hE4LqOClNO/1IWGxSmJjLLOJ8ktbeoKruU="
    # ^^ GPG_PASSPHRASE

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: ${SONAR_TOKEN}

before_script:
  - git clone https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/mirioeggmann/tbmelabs-deploy-certificates.git
  - gpg --fast-import tbmelabs-deploy-certificates/tbmelabs-deploy-key.asc
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean verify

after_script:
  - rm -rf tbmelabs-deploy-certificates

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
