language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

env:
  global:
    - secure: "VoE6pZohle083FEva+XA3d7od37X6d0J6Q3olh9WrA3lgBKH5cbKhApaqs3j9sWFijYm6Jt/PqA/K0UBS2LBoSveGY2dM8tHqJZKqbalt3HAcmlRlqmmH4mTuz3qTrQZvsBhidQpMkQs33m9texySziEYz9UFbqGNAEToKibj5u4WObmn3wJAzzxrE0H4NcORpEvG2aKI0arjQ93VSjuOAgv9TYF58DRRr1oyaAk2jxWpQ/P3qZoECa475lVwl22EMHnCafbvkrwCNCLNJT+s/z59pZruQEMicxISkXekNyH6ZURHJtdCcCLxI4/ni6vwiiWMX+8dI36PqD2XeXJJFfAXmjw1DuwooXsV0pWYBHgxvzPn/OPzr783+mrs2KpW8HT2nG+dNIjL8qZAbA9d5Yskfg86tlEn69B2Ban+PjSUNv+3OP6lNXJl+rKGFHr8UmTGDJOkQdSX5bP5eZrqfCNhWj72fJdPfop7ESPWH1JOv9aSUnLZcg4z4QnJaMrgUBEXetLhpcL0W/DpxasFM6VGr9+5rbWR71BXtmOZY/n5zkxhz7T7t25kY/V8RtKxxAyfVjzGgkeNVxH3RUP68bb5rL826U8a29I4rAebeq7HemUWHvnwd+TG6Imz5xum2400DVWwJiuEnULSNJbpyqhVmPK/Spd/CYkK977W2g="
    - secure: "thVtP6RD9oLKOUN7da9HvnEtzyFPoasE4BuKpsIEm7L5ArhoTVF4eIgBBsoo2wlvn5oFgSn0PZD576qnNrJGIlLGLSyt5Z4GyWaYLCLZfRvGX1sfKQJ1jo2mFN6OFGTBJLY3tq401xd32B8IsTOrkR1JDRvzrtSQh7C+/yaHznvMF5f0drU4ob1ZnYIxoDN/yqRS2hoGkZx47bj9cdyylcrwWUny5ypJ3u4GO4+vYfmEKO4Ubjn13F8r/ntMq25rPdXvjdEJlkCQ+yuigpJ+33Osml471W8VcjnyfAuwMP/6XPUNpdiL303P08rAo+ohjMLgFWKsKsHT/ybxRWvranSfAvlgUtrdpcfZso7V+vR9h8ii+B8vKOcysyzUfoIPQ5gmDq+MBDwcVo3r56l9haKUS9gu97LfArVIhSG5PhqcytUKxnQAIDHxl+bhpgcCMoxqeMcq7gfb2Lao1kLczV0J/ZHdIiiI3jInKLmEb+koQkuViiK033W9OTtAtu5acPqhmGdEa1s5kMFNUROBFEtS9VUkmi2MsTbZNke6B5VAdN8I6bS29fOkc4Zzn7rUFhGBWLihm2aWMJeFVKImaN67+noKg3Chs/BpX73Wg7frzJVLQ+3HikktOiiejGcwPUSpeVl8+tBJWRaHJHFS/3sLu7sIxW5tdQc95McFcc4="
    - secure: "Cbek3S9RCs9TIuUN8deQ0ZXU5PvANzA0hNhq54Y0e3/1Dn4QA7rIPeDnEnSBKWQwD/TPjSBPLjWID0AC+Xt97TK4qfd4T8h6NNP8k0FKN6jqDuHYTWKaj6odgqL0G10EDCe+1pxhXphesvIjBrZ+wVTqa/IMv7lNpI6SAWN7HIsU3HWI/Jlk0RqPKyuG3EYdwKsX7ZNECh5cwVOru77U+EFiPs/o25NhTh5pTPg29lxEihwqaRooWsyHiqG9ZP8o7+KTO2nAUJ3HOtODNy3+giTZkVk104JOqJ/UBCMvpYXvoMwfFK/geBIBdMfaRN85NYC2IMDOhvzVB0pJL6hl3UaTNqXoN+RLr6gMLdu0Xniop/DaA3GP1MOCJ7A1g4/g1htwLDqOYAzzhfzWbtySFpvVM1fWHw6+zU+fxn2Wrl2mWvsZvqWX4WslHtzXP7lAjGPJRK+Z8xel+KjkKxdv3l2XQtPDa5/95WL6aiwcxB09IMWxIFE8GnAcqjaLkFODvm1B6siKnMhC5oxIQFYYORukvIn2CLfk8GEHRuaMFaut65dbKrceUgGGYfk9FZ6fR2RC+r0PA8iWSnDOQwTTtbRcrBa2ihXgm/uetyuYdrBItohYSmXAvgOtuzVvgmxKcw43Iwg3/inzhD6f/RNr65Q2HfcAaBAyPvViJCfxiEg="
    - secure: "tCF2xE/3cO0wym3Of6p5iEmrGNAtrCdB8eWbJsrHHR8Jr5kfZjNwdPcymxpCDh8hUNOu2UNLVcu7UfQdVOGXqufotMEA7N2FD6rcB2c4IuWBU5hjjziLK3uDc1qYGF6RDm2yYRcVMq2g+p5CneJrdymAgOVnRAcA2njxYYEVJccKugsHhphPCDaoR4oaZlgg29LMfGj78N6X3VHzCCrt6lLNze8sJ8jBYChYfjWvnnH55iVp4vbMa4VzhTj4rRnGhmt6XB84KK424JeeacH7K4MPRc0lBsQf0jJR9WyPYzDnyJj0g3YcYwG/aNFkguHXwgj4KsonOhL9oVXklfffmfogsbPu/Cox9oc8TnJYaSFhlopV/Y3LHAMqu+PLafgKEcWIcSKYhbS+pZvs6CeA42PN4pGPUBhMYuV2tMxvu7kRVHomtHJ1ZhpH6qOte5v9gjzHypg9yqODFzGPoERwb1emTKjYRZJJWgd3Ftr1T4OP6Cy/gaDhGvH7iG0zezFf1FUMeJVDhCERLkK7jvuwlJPnRcAkOtVQgbWUc6j8U58EYV/UZD4bNva553JEEjzLwlll1zL58YC3+63YCxwC5BLK2vvX3+FYbFrEBDz0u+zW6UQZuQrgk8Cswc1PrD1pyxe7zlpDg+lfYYFCx90J8rl6L8sLgB4IPRfqXByc4jk="

# addons:
#   sonarcloud:
#     organization: "tbmelabs-github"
#     token:
#       secure: ${SONAR_TOKEN}

before_script:
  - openssl aes-256-cbc -K $encrypted_d11c1a306bcc_key -iv $encrypted_d11c1a306bcc_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --fast-import codesigning.asc
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script: |
  if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
    # mvn clean versions:set deploy -Psign,build-extras -DremoveSnapshot
  elif [[ $TRAVIS_BRANCH == "development" && $TRAVIS_PULL_REQUEST == "false" ]]; then
    mvn clean deploy -Pbuild-extras
  else
    mvn clean verify
  fi

after_script:
  - shred --remove codesigning.asc

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
