language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && ./scripts/deploy.sh"
  skip_cleanup: true

addons:
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: ${SONAR_TOKEN}

script:
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean install

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
